### ISSUE TITLE
Modifier la page des cafés (UI) pour donner plus de place aux éléments à caractère social.

### ISSUE THREAD

**Issue by lelafontant** [ceduni/cafe-sans-fil#50]
Dans la version 0.2.0, la page des cafés se concentre principalement sur la présentation du menu.
Puisque les cafés ont un fort caractère social (ex: organisation d'évènements, espace détente), l'interface doit traduire cela.
### TODO
- [x] Créer quelques prototypes visuels
- [x] Itérer avec les collaborateurs pour trouver le prototype gagnant
- [x] Implémenter le prototype choisi
