### ISSUE TITLE
Ajouter le support de fonctionnalités optionnelles

### ISSUE THREAD

**Issue by lelafontant** [ceduni/cafe-sans-fil#51]
Tous les cafés ne supportent pas les mêmes fonctionnalités (ex: _Prise de commande_).
Donc, il faut que l'application détermine pour chaque café les fonctionnalités à afficher/activer.

### TODO
- [ ] Définir la liste des fonctionnalités de l'application et leur attribuer un code.
- [x] Modifier l'entité café en BD pour répertorier les fonctionnalités (code) du café.
- [x] Modifier l'API pour retourner à l'application la liste des fonctionnalités du café
