### ISSUE TITLE
Ajouter la géolocalisation

### ISSUE THREAD

**Issue by lelafontant** [ceduni/cafe-sans-fil#52]
### TODO

- [ ] Ajouter les champs de géolocalisation au schéma _Cafe_ (GeoJSON Point)
- [ ] Modifier l'API pour supporter les requêtes utilisant la géolocalisation
- [ ] Modifier l'application pour supporter la géolocalisation
